Complete changelogs
LycheeOrg/LycheeOrg.github.io pull request #58
Opened 2022-06-13 06:26 UTC by qwerty287

Add changelogs prior v2.0 to have a completed list of them, taken from https://github.com/electerious/Lychee/tags.

2022-06-17 15:53 UTC, d7415 requested changes
I'm not sure how much use this is, but we already have changes from before LycheeOrg, so why not. Just a typo to fix.

2022-06-17 15:53 UTC, d7415 commented on docs/releases.md
> +Releaser October 2, 2012
```suggestion
Released October 2, 2012
```

2022-06-17 23:32 UTC, ildyria approved these changes

2022-06-18 08:36 UTC, d7415 approved these changes

2022-06-18 08:37 UTC, merged